name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Linux dependencies (X11)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

    - name: Linux dependencies (NVidia Container Tooklkit)
      run: >
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && 
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | 
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | 
        sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list &&
        sudo apt-get update &&
        sudo apt-get install -y nvidia-container-toolkit &&
        sudo nvidia-ctk runtime configure --runtime=docker &&
        sudo systemctl restart docker

    - name: Xvfb
      if: runner.os == 'Linux'
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    
    - name: Build the Docker image
      run: sudo docker compose build

    - name: Run the Docker image
      run: sudo docker compose up -d --no-recreate
